-- Organizations 1.0.21: organization members, roles and mandate history.
CREATE TABLE IF NOT EXISTS `#__xdecaroorganizations_appointments` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `uuid` CHAR(36) NOT NULL,
 `organization_id` INT UNSIGNED NOT NULL,
 `person_uuid` CHAR(36) NOT NULL,
 `person_name_snapshot` VARCHAR(255) NOT NULL,
 `role_code` VARCHAR(50) NOT NULL,
 `role_custom` VARCHAR(190) DEFAULT NULL,
 `starts_on` DATE NOT NULL,
 `planned_ends_on` DATE DEFAULT NULL,
 `ended_on` DATE DEFAULT NULL,
 `end_reason` VARCHAR(50) DEFAULT NULL,
 `end_note` TEXT DEFAULT NULL,
 `notes` TEXT DEFAULT NULL,
 `state` TINYINT NOT NULL DEFAULT 1,
 `created` DATETIME NOT NULL,
 `created_by` INT UNSIGNED NOT NULL DEFAULT 0,
 `modified` DATETIME DEFAULT NULL,
 `modified_by` INT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (`id`),
 UNIQUE KEY `idx_appointment_uuid` (`uuid`),
 KEY `idx_appointment_org` (`organization_id`),
 KEY `idx_appointment_person` (`person_uuid`),
 KEY `idx_appointment_org_dates` (`organization_id`,`starts_on`,`planned_ends_on`),
 KEY `idx_appointment_state` (`state`),
 CONSTRAINT `fk_xdecaroorganizations_appointment_org` FOREIGN KEY (`organization_id`) REFERENCES `#__xdecaroorganizations_organizations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
